project:
  type: book
  output-dir: ../../docs/mathematical-analysis

book:
  title: "Mathematical Analysis"
  author: "Guillaume Gilles"
  date: "1/27/2026"
  search: 
    location: sidebar
  navbar:
    right:
      - href: ../about/README.html
      - href: ../blog.html
 
  chapters:
    - index.qmd
    - part: "**UNIVARIATE**"
      chapters:
      - derivatives.qmd
      - elasticity-1.qmd
      - intro-optimization.qmd
    - part: "**BIVARIATE**"
      chapters:
      # Chapter 3
      - bivariate.qmd
      # Chapter 4
      - matrices.qmd
    - part: "**INTRODUCTION TO OPERATIONAL RESEARCH**"
      chapters:
      # Chapter 5
      - operations-research.qmd
    # References
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: light.scss

