project:
  type: book
  output-dir: ../../docs/mathematical-analysis

book:
  title: "Mathematical Analysis"
  author: "Guillaume Gilles"
  date: "1/27/2026"
  search: 
    location: sidebar
  navbar:
    right:
      - href: ../about/index.html
        text: "About"
      - href: ../index.html
        text: "Projects"
 
  chapters:
    - index.qmd
    - part: "UNIVARIATE"
      chapters:
      # Chapter 1
      - derivatives.qmd
      # Chapter 2
      - intro-math-optimization.qmd
    - part: "BIVARIATE"
      chapters:
      # Chapter 3
      - bivariate.qmd
      # Chapter 4
      - matrices.qmd
    - part: "INTRODuCTiON TO OPERATIONAL RESEARCH"
      chapters:
      # Chapter 5
      - operations-research.qmd
    # References
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: light.scss

